---
title: "hw3"
author: "Ying Xiang"
date: "3/19/2021"
output:
  pdf_document: default
  html_document: default
---

```{r}
#1
library(e1071)
data5=read.table("train_5.txt",sep=",")
data6=read.table("train_6.txt",sep=",")
y5=rep(-1,nrow(data5))
y6=rep(1,nrow(data6))
wholedata=data.frame(label=as.factor(c(y5,y6)),rbind(data5,data6))
```

```{r}
groupsize=nrow(wholedata)*0.2

index=sample(1:nrow(wholedata),size=nrow(wholedata))
grouprows1=index[1:groupsize]
grouprows2=index[(1+groupsize):(2*groupsize)]
grouprows3=index[(1+2*groupsize):(3*groupsize)]
grouprows4=index[(1+3*groupsize):(4*groupsize)]
grouprows5=index[(1+4*groupsize):(5*groupsize)]

```

```{r}
#1.1.a
options(warn = -1)
misclass_error_linear=rep(NA,5)
counter=1
cost=c("1","10","100","1000","10000")
for (i in 10^(0:4)){
  options(warn = -1)
  linearsvm1=svm(label~.,data=wholedata[-grouprows1,],kernel="linear",cost=i)
  linearsvm2=svm(label~.,data=wholedata[-grouprows2,],kernel="linear",cost=i)
  linearsvm3=svm(label~.,data=wholedata[-grouprows3,],kernel="linear",cost=i)
  linearsvm4=svm(label~.,data=wholedata[-grouprows4,],kernel="linear",cost=i)
  linearsvm5=svm(label~.,data=wholedata[-grouprows5,],kernel="linear",cost=i)
  misclass_error1=mean(wholedata[grouprows1,]$label!=predict(linearsvm1,wholedata[grouprows1,]))
  misclass_error2=mean(wholedata[grouprows2,]$label!=predict(linearsvm2,wholedata[grouprows2,]))
  misclass_error3=mean(wholedata[grouprows3,]$label!=predict(linearsvm3,wholedata[grouprows3,]))
  misclass_error4=mean(wholedata[grouprows4,]$label!=predict(linearsvm4,wholedata[grouprows4,]))
  misclass_error5=mean(wholedata[grouprows5,]$label!=predict(linearsvm5,wholedata[grouprows5,]))
  
  
  
  misclass_error_linear[counter]=mean(c(misclass_error1,misclass_error2,misclass_error3,misclass_error4,misclass_error5))
  counter=counter+1
}

plot(factor(cost),misclass_error_linear,type="l")

```


```{r}
#1.1.b
misclass_error_radial=data.frame("6"=rep(NA,6),"5"=rep(NA,6),"4"=rep(NA,6),"3"=rep(NA,6),"2"=rep(NA,6),"1"=rep(NA,6))
c=10^(0:5)
g=10^(-6:-1)
for (i in (1:6)){
  for (j in (1:6)){
    
    rbfsvm1=svm(label~.,data=wholedata[-grouprows1,],kernel="radial",cost=c[i],gamma=g[j])
    rbfsvm2=svm(label~.,data=wholedata[-grouprows2,],kernel="radial",cost=c[i],gamma=g[j])
    rbfsvm3=svm(label~.,data=wholedata[-grouprows3,],kernel="radial",cost=c[i],gamma=g[j])
    rbfsvm4=svm(label~.,data=wholedata[-grouprows4,],kernel="radial",cost=c[i],gamma=g[j])
    rbfsvm5=svm(label~.,data=wholedata[-grouprows5,],kernel="radial",cost=c[i],gamma=g[j])
    misclass_error1=mean(wholedata[grouprows1,]$label!=predict(rbfsvm1,wholedata[grouprows1,]))
    misclass_error2=mean(wholedata[grouprows2,]$label!=predict(rbfsvm2,wholedata[grouprows2,]))
    misclass_error3=mean(wholedata[grouprows3,]$label!=predict(rbfsvm3,wholedata[grouprows3,]))
    misclass_error4=mean(wholedata[grouprows4,]$label!=predict(rbfsvm4,wholedata[grouprows4,]))
    misclass_error5=mean(wholedata[grouprows5,]$label!=predict(rbfsvm5,wholedata[grouprows5,]))
    
    misclass_error_radial[i,j]=mean(c(misclass_error1,misclass_error2,misclass_error3,misclass_error4,misclass_error5))
  }
}
```

```{r}
heatmap(as.matrix(misclass_error_radial),scale="none",xlab="gamma",ylab="cost")
misclass_error_radial
min(misclass_error_radial)
```

```{r}
#1.2
#misclassification rate for linear case(cost=100)
misclass_error_linear
#misclassification rate for non-linear case(cost=100,gamma=10^-3)
min(misclass_error_radial)
#should use non-linear SVM.
```


```{r}
#2.5
data2=read.csv("HW3Problem2.csv")
library(ggplot2)
ggplot(data2,aes(x=x1,y=x2,color=class))+geom_point()
data_2=data2
data_2$class=as.factor(c(rep(1,201),rep(-1,201)))
```

```{r}
#First, find best cost by using tune.svm()
tuned=tune.svm(class~.,data=data_2,gamma=10^(-4:2),cost=10^(0:3))
summary(tuned)
#cost=10
```

```{r}
for (i in 10^(-1:2)){
  p2svm=svm(class~.,data=data_2,kernel="radial",cost=10,gamma=i)
plot(p2svm,data_2,x2~x1)}

#bandwidths from 10^-1 to 10^2
```

```{r}
#3.i
x=seq(-1,3,0.01)
g=rep(NA,length(x))
for (i in 1:length(x)){
  g[i]=max(0,1-x[i])
}

plot(x,g,type="l")
```

```{r}
#3.iii
data3=read.csv("svmdata.csv")
lambda=0.25
beta=c(0,0,0)
z=rep(NA,100)
del_Qi=data.frame(Qi_c=rep(NA,100),Qi_w1=rep(NA,100),Qi_w2=rep(NA,100))
for (t in 1:10000){
for (i in 1:100){
  z[i]=data3$y[i]*(beta[1]+beta[2]*data3$x1[i]+beta[3]*data3$x2[i])
  if (z[i]>1) {
    del_Qi[i,]=c(0,lambda*beta[2],lambda*beta[3])
  }
  if (z[i]<1){
    del_Qi[i,]=c(-data3$y[i],lambda*beta[2]-data3$y[i]*data3$x1[i],lambda*beta[3]-data3$y[i]*data3$x2[i])
  }
}
del_Q=c(mean(del_Qi$Qi_c),mean(del_Qi$Qi_w1),mean(del_Qi$Qi_w2))
if (((1/t/0.25)*del_Q[1]<10^(-10)) & ((1/t/0.25)*del_Q[2]<10^(-10)) & ((1/t/0.25)*del_Q[3]<10^(-10))){
  print(t)
  break
}
beta=beta-(1/t/0.25)*del_Q
}
```


```{r}
plot(data3$x1,data3$x2,col=(data3$y+2))
x1=seq(-4,1,0.01)
x2=-beta[2]/beta[3]*x1-beta[1]/beta[3]
lines(x1,x2)
```


```{r}
data_3=data3
data_3$y=as.factor(data_3$y)
p3svm=svm(y~.,data=data_3,kernel="linear",cost=100000)
plot(p3svm,data_3,x2~x1)

```

```{r}
# The  estimated linear decision boundary from 3.iii is close to the boundary from function svm()

beta
```
